### ISSUE TITLE
请问只能在windows上运行吗？mac或者linux可以运行吗？

### ISSUE THREAD

**Issue by ArlanCooper** [rpaii-com/II-RPA#3]
请问只能在windows上运行吗？mac或者linux可以运行吗？

**Comment by lbnkrxct** [comment]
目前是只支持Windows，现在正在弄linux的适配，mac的可能会稍晚一些，




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "rpaii-com/II-RPA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月29日(星期三) 中午11:51
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[rpaii-com/II-RPA] 请问只能在windows上运行吗？mac或者linux可以运行吗？ (#3)





 
请问只能在windows上运行吗？mac或者linux可以运行吗？
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ArlanCooper** [comment]
> 目前是只支持Windows，现在正在弄linux的适配，mac的可能会稍晚一些，
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "rpaii-com/II-RPA" ***@***.***&gt;; 发送时间:&nbsp;2021年9月29日(星期三) 中午11:51 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[rpaii-com/II-RPA] 请问只能在windows上运行吗？mac或者linux可以运行吗？ (#3) 请问只能在windows上运行吗？mac或者linux可以运行吗？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

好的，谢谢
